Todo

* IDEAS
  - Deck building elements.
  - Skill points. Skills cost varying amounts of points.
  - Random item/card modifiers like in an action-rpg.
  - Integrated detonator and "mana" system.
  - Levels/waves should feel like open-ended puzzles.
  - Economy. What are the resources in the game?
  - What elements are in balance? What does progression look like?
  - Ammo system.
  - Slow the game down.
  - Part of the fun is combining things, like the SABER and HOMING.
  - Unique items. Firebrand. Icebrand.
  - Armor items.
  - Every weapon should be awesome and incredibly satisfying.

* DEV
  - Iteration and feedback-cycle should be as rapid as possible.
  - [ ] Add as much logging as possible (with data). You need a way detect bugs/crashes
    during iterations.
  - [ ] Use event/data-payload system. This should help with finding bugs/crashes.
  - [ ] Add as many tests as you can and run the tests automatically every
    reload. Regression tests are extremely useful.

* UI
  1) [X] Move weapon and powerup bar to near bottom of screen and make the bars
     and text bigger for readability.
  2) [ ] Show inflicted damage overhead enemy units (white) and also against you (red).

* GAMEPLAY
  1) [ ] Gameplay overhaul. Detonators should now be a finite resource. You
     start with 10 detonations. Detonators spawn randomly around the map at N
     (random) interval. Detonators are a separate pool from powerups and
     weapons, so they're not affected by those particular limits.
  2) [ ] Waves should last longer and each wave should have a theme.
  3) [ ] Start with 5 detonators.
  4) [ ] Recoil system. Some weapons push the player back and/or slow them down.
  5) [ ] Remove default magnetic powerups. This will be used as a skill.
  6) [ ] Add a wave timer to show the current wave duration.
  7) [ ] If the player runs out of detonator caps, a long cooldown is initiated
     where on ending a cap is restored.
  8) [ ] Disable shrapnel on death.
  9) [ ] Scale damage. Pistol 9-13 default.

* RHYTHM, GAME LOOP
  1) [ ] The game should have more "rhythm." Currently, it feels like just
     nonstop waves coming at you. There should be lulls, extreme wave numbers,
     sometimes just a few large enemies or a boss and a few minions. The game
     should "feel" right, like there's some progression. Some level of
     predictability should be inherent, otherwise it just feels like a nonstop,
     random, but predictable mess.

* TWEAKS
  1) [ ] Make SABER repel distance greater and increase stun time.
  2) [ ] Make GRENADE animation start out fast then slow down as it reaches its target.

* PLAYER
  1) [X] Level up window is abrupt. Show a level up visual like a golden glow
     around the player then a few seconds later show the screen.

* SPAWNS
  1) [X] Add SPAWNER spawn type. This particular unit is slow and tanky. It
     spawns units around itself until it's destroyed.
  2) [X] Add RUNNER spawn type. This unit is weak but moves more quickly than
     others.
  3) [X] Add ELECTRIC spawn type. This unit spawns an electric field around
     itself every N interval that can damage the player.
  4) [X] Add HIVE spawn type. This units spawns somewhere on the map (not the
     edge. It is larger, immobile, and very tanky. It spawns critter units very
     quickly. Similar to SPAWNER, but more extreme.
  5) [X] Make HIVE unit bigger. It should be differentiated from other large
     enemy units.
  6) [X] HIVE should be much tankier. It's too easy to kill.
  7) [ ] Implement RARE spawn types. Rare units are like normal units but have
     boosted stats. RARE is a modifier applied to an existing unit.
     Differentiate the unit visually. Rare units can also have one or more skills
     (see below).
  8) [ ] Implement spawn skills. Skills are modifiers to stats or abilities. For example:
     - High durability
     - Super high durability
     - Extra speed
     - Smooth (bullets and shrapnel cannot stick to this unit). Can only be
       damaged by detonations.
     - Splits itself in two every N interval (with existing hitpoints).
     - Absorbs bullets and shrapnel around itself every N interval.
     - High regen.
     - Regen field in AoE around itself.
     - Kamikaze. Does extra damage and destroys itself on contact with player.
  9) [ ] FIREWALKER. This unit leaves a trail of damaging fire in its
     wake. It has moderately fast walk speed. Fire trail cannot be damaged. It
     goes away after N seconds.
  10) [ ] Add TELEPORTER spawn type. This units moves by short teleportations.
  11) [ ] Add GLOBBER spawn. This unit consumes small spawns around itself,
      adding to its life and size. The life added is a multiplier of the unit
      consumed.
  12) [ ] Add DASHER spawn type. This unit has the ability to dash towards the
      player when it gets close.
  13) [ ] ADD CHAMPION spawn type. This is a powerful combat unit that will
      resurrect once upon death. When it dies, its laid to rest briefly. An
      animation and effect occurs where the unit is revived.
  14) [ ] Add HYDRA spawn type. This is a unit that immediately splits into two
      upon death. The HYDRA can split twice before dying permanently.

* WEAPONS
  1) [X] Add currency and weapon system. Enemies give gold on kill. Gold can be
     used to purchase weapons. Weapons can be purchased or switched on the LEVEL
     UP menu.
  2) [X] Add new base weapon types.
  3) [X] Add GRENADE weapon type. It lobs a grenade at the reticle. When it
     lands and explodes, it creates a ring of shrapnel in random directions.
  4) [X] Minigun should fire in a random spray pattern.
  5) [X] Shotgun should have high base projectile velocity.
  6) [ ] Reduce shrapnel count on grenade to 16.
  7) [ ] Add BUG weapon. This weapon "bites" enemies, creating shrapnel on the
     stuck enemy, then jumps to the next enemy after a few "bites." It lasts for
     N duration.
  8) [ ] Add SCATTERGUN. This is a rapid-firing, short-range weapon with wide
     spread and large bullets. The bullets are slow-moving and expire after a
     brief period of time.
  9) [X] Add SABER melee weapon. Melee weapons are a new class of weapon that
     deal direct damage to enemies. The SABER has a secondary effect where it
     "charges" an enemy with an incremental "charge count." When a charged
     enemy dies, it detonates nearby shrapnel and other charged enemies for
     damage. Each charge stack deals additional damage. Charged enemies should
     glow yellow. Show the charge count also on top of the enemy. CHARGE is a
     unique mechanic that will be reused.
  10) [X] Add LANCE melee weapon. LANCE is similar to SABER, but attacks in a
      long straight triangle with the tip at the furthest point. It's secondary
      ability (right-click) fires a spear projectile in the direction of the
      cursor, damaging enemies in its path. Like SABER, show a charge effect
      around the player. The theme color of the lance is GREEN whereas SABER is
      BLUE.
  11) [ ] Add HALBERD melee weapon. The theme color of the halberd is RED.
      Halberd attacks in a wide area and inflicts a "burn" debuff which deals
      damage over time. Burn debuffs can stack. The secondary ability of HALBERD
      immolates the player for 5 seconds, dealing damage to enemies around him
      over time. The ability has a 17 second cooldown.
  12) [X] Clamp pistol spread arc to 45 degrees.
  13) [ ] Add GLITTER GUN. This fires ballistically similar to the SCATTERGUN,
      but fires special slowing bullets. The bullets have a special detonation
      effect where affected units "burn" for damage over time permanently until
      they die.
  14) [ ] Add FLARE weapon. This is a powerful weapon with 3 charges. It's a
      rare projectile weapon that deals DIRECT DAMAGE. The weapon fires a large
      projectile that deals tremendous damage to any enemy unit in its path.
  15) [ ] Add GRAVITY gun. This lobbing weapon (like the grenade) pulls units
      toward its landing site (doesn't affect extra large enemy types). It deals
      no damage and does not create shrapnel. Units affected are slowing down by
      a rate of 0.5.
  16) [ ] Not all weapons should be affected by skills equally. Some weapons
      should have a threshold where they are affected. For example, GRENADE
      should only gain a projectile count every 2 extra bullet skill points. Whereas
      the SHOTGUN should gain 2x projectiles for every point.
  17) [ ] Add MACHINE GUN weapon type. This weapon is similar to the minigun,
      but has a slow rate of fire, less spread, less recoil, less slow-on-fire.
      Fires in bursts.
  18) [X] Powerups and skills should work with SABER. SPREAD should increase arc
      range (with a reasonable limit). DOUBLE TAP should add an additional saber
      strike after a brief delay. BIG BULLETS should increase range.
  19) [X] Remove LANCE burst effect.
  20) [ ] Add ORB weapon. ORB throws out a slow moving glowing orb which
      releases BLUE SHRAPNEL around itself in a spiral pattern. BLUE SHRAPNEL
      slows down enemies it attaches to.

* DETONATORS

* ITEMS
  1) [X] Items should float slowly randomly, but should not be attracted to the player.

* POWERUPS
  1) [X] Powerups scale scale with the player's base stats when possible. For
     example, spread/multi should apply a multiplier to the current bullet
     quantity.
  2) [ ] Add SENTRY powerup. This powerup spawns an auto-firing sentry at the
     location of the powerup.
  3) [ ] ADD PHASE powerup. This powerup allows you to walk through enemies
     without taking damage.
  4) [ ] Make SHIELD permanent. SHIELD protects you from damage for a single hit.
  5) [ ] Add BARBS powerup. This powerup slows down any enemies affected by
     attached shrapnel (only when fired when BARBS was active, not affecting
     existing shrapnel).
  6) [ ] Add ECHO powerup. This powerup causes a delayed "echo" of your weapon
     whenever fired. For example, if you fire a shotgun, a 100ms later, another
     shotgun blast will fire on its own as in an "echo."

* ENVIRONMENT
  1) [ ] Add TNT environment object. This is a stationary object that looks like
     a red metal barrel. It explodes when its hitpoints are depleted.

* SKILLS
  1) [X] Remove FAST LEARNER skill.
  2) [X] Remove VAMPIRIC skill.
  3) [ ] Add skill ENGINEER to increase detonator limit.
  4) [ ] Add MAGICIAN skill.
  5) [ ] Add JUGGLER skill. Picked up weapons will be queued up and used when
     the current one expires.
  6) [ ] Add FAR-SEER skill. This increases the powerup spawn limit
     incrementally.
  7) [ ] Add MAGNETIC skill. This skill attract items to you. More points
     increase the attraction radius, diminishing exponentially.
  8) [ ] Add THORNS skill. Enemies take a lot of damage when they attack you.

* VISUALS
  1) [X] Make weapon items distinct from powerups.
  2) [X] Powerups and weapon item drops should have a label underneath them.
  3) [ ] Add cap to explosion radius visual effect.
  4) [X] Show lifebars on large units.

* PERF
  1) [ ] What is the main performance bottleneck?

* DEBUG

* BUGS
  1) [X] Powerups don't seem to affect grenade weapon.
  2) [X] GRENADE weapon type is doing direct damage.
  3) [ ] You can click rapidly to ignore weapon cooldown. This bug was probably
     introduced when fixing the other bug where weapons don't fire immediately
     on mouse-down.
  4) [ ] Reticle lags (get stuck for a brief moment) when you left or right-click.
  5) [ ] You can detonate on the pause screen.
  6) [ ] Lance doesn't have a triangular hitbox.

* PRODUCTION
  Platforms: Switch, Steam
