Todo

* HUD
  1) [X] Move weapon and powerup bar to near bottom of screen and make the bars
     and text bigger for readability.

* GAMEPLAY
  1) [ ] Gameplay overhaul. Detonators should now be a finite resource. You
     start with 10 detonations. Detonators spawn randomly around the map at N
     (random) interval. Detonators are a separate pool from powerups and
     weapons, so they're not affected by those particular limits.
  2) [ ] Waves should last longer and each wave should have a theme.

* PLAYER
  1) [ ] Level up window is abrupt. Show a level up visual like a golden glow
     around the player then a few seconds later show the screen.

* ENEMY TYPES
  1) [X] Add SPAWNER enemy type. This particular unit is slow and tanky. It
     spawns enemy units around itself until it's destroyed.
  2) [X] Add RUNNER enemy type. This unit is weak but moves more quickly than
     others.
  3) [X] Add ELECTRIC enemy type. This unit spawns an electric field around
     itself every N interval that can damage the player.
  4) [X] Add HIVE enemy type. This units spawns somewhere on the map (not the
     edge. It is larger, immobile, and very tanky. It spawns critter units very
     quickly. Similar to SPAWNER, but more extreme.
  5) [X] Make HIVE unit bigger. It should be differentiated from other large
     enemy units.
  6) [X] HIVE should be much tankier. It's too easy to kill.
  7) [ ] Implement RARE enemy types. Rare units are like normal units but have
     boosted stats. RARE is a modifier applied to an existing unit.
     Differentiate the unit visually. Rare units can also have one or more perks
     (see below).
  8) [ ] Implement enemy perks. Perks are modifiers to stats or abilities. For example:
     - High durability
     - Super high durability
     - Extra speed
     - Smooth (bullets and shrapnel cannot stick to this unit). Can only be
       damaged by detonations.
     - Splits itself in two every N interval (with existing hitpoints).
     - Absorbs bullets and shrapnel around itself every N interval.
     - High regen.
     - Regen field in AoE around itself.
     - Kamikaze. Does extra damage and destroys itself on contact with player.
  9) [ ] FIREWALKER. This enemy unit leaves a trail of damaging fire in its
     wake. It has moderately fast walk speed. Fire trail cannot be damaged. It
     goes away after N seconds.

* WEAPONS
  1) [X] Add currency and weapon system. Enemies give gold on kill. Gold can be
     used to purchase weapons. Weapons can be purchased or switched on the LEVEL
     UP menu.
  2) [X] Add new base weapon types.
  3) [ ] Add GRENADE weapon type. It lobs a grenade at the reticle. When it
     lands and explodes, it creates a ring of shrapnel in random directions.
  4) [X] Minigun should fire in a random spray pattern.

* POWERUPS
  1) [X] Powerups scale scale with the player's base stats when possible. For
     example, spread/multi should apply a multiplier to the current bullet
     quantity.

* PERKS
  1) [ ] Remove FAST LEARNER perk.
  2) [ ] Remove VAMPIRIC perk.

* VISUALS
  1) [ ] Make explosions red in color.
  2) [ ] Make weapon items distinct from powerups.

* PERF
  1) [ ] What is the main performance bottleneck?
