Todo

* HUD
  1) [ ] Move weapon and powerup bar to near bottom of screen and make the bars
     and text bigger for readability.

* GAMEPLAY
  1) [ ] Gameplay overhaul. Detonators should now be a finite resource. You
     start with 10 detonations. Detonators spawn randomly around the map at N
     (random) interval. Detonators are a separate pool from powerups and
     weapons, so they're not affected by those particular limits.

* ENEMY TYPES
  1) [X] Add SPAWNER enemy type. This particular unit is slow and tanky. It
     spawns enemy units around itself until it's destroyed.
  2) [X] Add RUNNER enemy type. This unit is weak but moves more quickly than
     others.
  3) [X] Add ELECTRIC enemy type. This unit spawns an electric field around
     itself every N interval that can damage the player.
  4) [X] Add HIVE enemy type. This units spawns somewhere on the map (not the
     edge. It is larget, immobile, and very tanky. It spawns critter units very
     quickly. Similar to SPAWNER, but more extreme.

* WEAPONS
  1) [X] Add currency and weapon system. Enemies give gold on kill. Gold can be
     used to purchase weapons. Weapons can be purchased or switched on the LEVEL
     UP menu.
  2) [X] Add new base weapon types.
  3) [ ] Add GRENADE weapon type. It lobs a grenade at the reticle. When it
     lands and explodes, it creates a ring of shrapnel in random directions.
  4) [ ] Minigun should fire in a random spray pattern.

* POWERUPS
  1) [X] Powerups scale scale with the player's base stats when possible. For
     example, spread/multi should apply a multiplier to the current bullet
     quantity.

* PERKS
  1) [ ] Remove FAST LEARNER perk.

* VISUALS
  1) [ ] Make explosions red in color.
