Todo

* HUD
  1) [X] Move weapon and powerup bar to near bottom of screen and make the bars
     and text bigger for readability.

* GAMEPLAY
  1) [ ] Gameplay overhaul. Detonators should now be a finite resource. You
     start with 10 detonations. Detonators spawn randomly around the map at N
     (random) interval. Detonators are a separate pool from powerups and
     weapons, so they're not affected by those particular limits.
  2) [ ] Waves should last longer and each wave should have a theme.
  3) [ ] Start with 5 detonators.
  4) [ ] Recoil system. Some weapons push the player back and/or slow them down.
  5) [ ] Remove default magnetic powerups. This will be used as a skill.

* PLAYER
  1) [X] Level up window is abrupt. Show a level up visual like a golden glow
     around the player then a few seconds later show the screen.

* SPAWNS
  1) [X] Add SPAWNER spawn type. This particular unit is slow and tanky. It
     spawns units around itself until it's destroyed.
  2) [X] Add RUNNER spawn type. This unit is weak but moves more quickly than
     others.
  3) [X] Add ELECTRIC spawn type. This unit spawns an electric field around
     itself every N interval that can damage the player.
  4) [X] Add HIVE spawn type. This units spawns somewhere on the map (not the
     edge. It is larger, immobile, and very tanky. It spawns critter units very
     quickly. Similar to SPAWNER, but more extreme.
  5) [X] Make HIVE unit bigger. It should be differentiated from other large
     enemy units.
  6) [X] HIVE should be much tankier. It's too easy to kill.
  7) [ ] Implement RARE spawn types. Rare units are like normal units but have
     boosted stats. RARE is a modifier applied to an existing unit.
     Differentiate the unit visually. Rare units can also have one or more skills
     (see below).
  8) [ ] Implement spawn skills. Skills are modifiers to stats or abilities. For example:
     - High durability
     - Super high durability
     - Extra speed
     - Smooth (bullets and shrapnel cannot stick to this unit). Can only be
       damaged by detonations.
     - Splits itself in two every N interval (with existing hitpoints).
     - Absorbs bullets and shrapnel around itself every N interval.
     - High regen.
     - Regen field in AoE around itself.
     - Kamikaze. Does extra damage and destroys itself on contact with player.
  9) [ ] FIREWALKER. This unit leaves a trail of damaging fire in its
     wake. It has moderately fast walk speed. Fire trail cannot be damaged. It
     goes away after N seconds.
  10) [ ] Add TELEPORTER spawn type. This units moves by short teleportations.
  11) [ ] Add GLOBBER spawn. This unit consumes small spawns around itself,
      adding to its life and size. The life added is a multiplier of the unit
      consumed.
  12) [ ] Add DASHER spawn type. This unit has the ability to dash towards the
      player when it gets close.
  13) [ ] ADD CHAMPION spawn type. This is a powerful combat unit that will
      resurrect once upon death. When it dies, its laid to rest briefly. An
      animation and effect occurs where the unit is revived.
  14) [ ] Add HYDRA spawn type. This is a unit that immediately splits into two
      upon death. The HYDRA can split twice before dying permanently.

* WEAPONS
  1) [X] Add currency and weapon system. Enemies give gold on kill. Gold can be
     used to purchase weapons. Weapons can be purchased or switched on the LEVEL
     UP menu.
  2) [X] Add new base weapon types.
  3) [X] Add GRENADE weapon type. It lobs a grenade at the reticle. When it
     lands and explodes, it creates a ring of shrapnel in random directions.
  4) [X] Minigun should fire in a random spray pattern.
  5) [X] Shotgun should have high base projectile velocity.
  6) [ ] Reduce shrapnel count on grenade to 16.
  7) [ ] Add BUG weapon. This weapon "bites" enemies, creating shrapnel on the
     stuck enemy, then jumps to the next enemy after a few "bites." It lasts for
     N duration.
  8) [ ] Add SCATTERGUN. This is a rapid-firing, short-range weapon with wide
     spread and large bullets. The bullets are slow-moving and expire after a
     brief period of time.
  9) [ ] Add SABER melee weapon. Melee weapons are a new class of weapon that
     deal direct damage to enemies. The SABER has a secondary effect where it
     "charges" an enemy with an incremental "charge count." When a charged
     enemy dies, it detonates nearby shrapnel and other charged enemies for
     damage. Each charge stack deals additional damage. Charged enemies should
     glow yellow. Show the charge count also on top of the enemy. CHARGE is a
     unique mechanic that will be reused.
  10) [ ] Add HALBERD melee weapon.
  11) [ ] Add LANCE melee weapon.
  12) [X] Clamp pistol spread arc to 45 degrees.
  13) [ ] Add GLITTER GUN. This fires ballistically similar to the SCATTERGUN,
      but fires special slowing bullets. The bullets have a special detonation
      effect where affected units "burn" for damage over time permanently until
      they die.
  14) [ ] Add FLARE weapon. This is a powerful weapon with 3 charges. It's a
      rare projectile weapon that deals DIRECT DAMAGE. The weapon fires a large
      projectile that deals tremendous damage to any enemy unit in its path.
  15) [ ] Add GRAVITY gun. This lobbing weapon (like the grenade) pulls units
      toward its landing site (doesn't affect extra large enemy types). It deals
      no damage and does not create shrapnel. Units affected are slowing down by
      a rate of 0.5.
  16) [ ] Not all weapons should be affected by skills equally. Some weapons
      should have a threshold where they are affected. For example, GRENADE
      should only gain a projectile count every 2 extra bullet skill points. Whereas
      the SHOTGUN should gain 2x projectiles for every point.

* DETONATORS

* POWERUPS
  1) [X] Powerups scale scale with the player's base stats when possible. For
     example, spread/multi should apply a multiplier to the current bullet
     quantity.
  2) [ ] Add SENTRY powerup. This powerup spawns an auto-firing sentry at the
     location of the powerup.
  3) [ ] ADD PHASE powerup. This powerup allows you to walk through enemies
     without taking damage.
  4) [ ] Make SHIELD permanent. SHIELD protects you from damage for a single hit.
  5) [ ] Add BARBS powerup. This powerup slows down any enemies affected by
     attached shrapnel (only when fired when BARBS was active, not affecting
     existing shrapnel).

* SKILLS
  1) [X] Remove FAST LEARNER skill.
  2) [X] Remove VAMPIRIC skill.
  3) [ ] Add skill ENGINEER to increase detonator limit.
  4) [ ] Add MAGICIAN skill.
  5) [ ] Add JUGGLER skill. Picked up weapons will be queued up and used when
     the current one expires.
  6) [ ] Add FAR-SEER skill. This increases the powerup spawn limit
     incrementally.
  7) [ ] Add MAGNETIC skill. This skill attract items to you. More points
     increase the attraction radius, diminishing exponentially.

* VISUALS
  1) [X] Make weapon items distinct from powerups.
  2) [X] Powerups and weapon item drops should have a label underneath them.
  3) [ ] Add cap to explosion radius visual effect.
  4) [X] Show lifebars on large units.

* PERF
  1) [ ] What is the main performance bottleneck?

* DEBUG

* BUGS
  1) [X] Powerups don't seem to affect grenade weapon.
  2) [X] GRENADE weapon type is doing direct damage.

* PRODUCTION
  Platforms: Switch, Steam
