Todo

* HUD
  1) [X] Move weapon and powerup bar to near bottom of screen and make the bars
     and text bigger for readability.

* GAMEPLAY
  1) [ ] Gameplay overhaul. Detonators should now be a finite resource. You
     start with 10 detonations. Detonators spawn randomly around the map at N
     (random) interval. Detonators are a separate pool from powerups and
     weapons, so they're not affected by those particular limits.
  2) [ ] Waves should last longer and each wave should have a theme.
  3) [ ] Start with 5 detonators.

* PLAYER
  1) [X] Level up window is abrupt. Show a level up visual like a golden glow
     around the player then a few seconds later show the screen.

* SPAWN TYPES
  1) [X] Add SPAWNER spawn type. This particular unit is slow and tanky. It
     spawns units around itself until it's destroyed.
  2) [X] Add RUNNER spawn type. This unit is weak but moves more quickly than
     others.
  3) [X] Add ELECTRIC spawn type. This unit spawns an electric field around
     itself every N interval that can damage the player.
  4) [X] Add HIVE spawn type. This units spawns somewhere on the map (not the
     edge. It is larger, immobile, and very tanky. It spawns critter units very
     quickly. Similar to SPAWNER, but more extreme.
  5) [X] Make HIVE unit bigger. It should be differentiated from other large
     enemy units.
  6) [X] HIVE should be much tankier. It's too easy to kill.
  7) [ ] Implement RARE spawn types. Rare units are like normal units but have
     boosted stats. RARE is a modifier applied to an existing unit.
     Differentiate the unit visually. Rare units can also have one or more skills
     (see below).
  8) [ ] Implement spawn skills. Skills are modifiers to stats or abilities. For example:
     - High durability
     - Super high durability
     - Extra speed
     - Smooth (bullets and shrapnel cannot stick to this unit). Can only be
       damaged by detonations.
     - Splits itself in two every N interval (with existing hitpoints).
     - Absorbs bullets and shrapnel around itself every N interval.
     - High regen.
     - Regen field in AoE around itself.
     - Kamikaze. Does extra damage and destroys itself on contact with player.
  9) [ ] FIREWALKER. This unit leaves a trail of damaging fire in its
     wake. It has moderately fast walk speed. Fire trail cannot be damaged. It
     goes away after N seconds.
  10) [ ] Add TELEPORTER spawn type. This units moves by short teleportations.

* WEAPONS
  1) [X] Add currency and weapon system. Enemies give gold on kill. Gold can be
     used to purchase weapons. Weapons can be purchased or switched on the LEVEL
     UP menu.
  2) [X] Add new base weapon types.
  3) [X] Add GRENADE weapon type. It lobs a grenade at the reticle. When it
     lands and explodes, it creates a ring of shrapnel in random directions.
  4) [X] Minigun should fire in a random spray pattern.
  5) [X] Shotgun should have high base projectile velocity.
  6) [ ] Reduce shrapnel count on grenade to 16.
  7) [ ] Add BUG weapon. This weapon "bites" enemies, creating shrapnel on the
     stuck enemy, then jumps to the next enemy after a few "bites." It lasts for
     N duration.
  8) [ ] Add SCATTERGUN. This is a rapid-firing, short-range weapon with wide
     spread and large bullets. The bullets are slow-moving and expire after a
     brief period of time.
  10) [ ] Add SABER melee weapon. Melee weapons are a new class of weapon that
      deal direct damage to enemies. The SABER has a secondary effect where it
      "charges" an enemy with an incremental "charge count." When a charged
      enemy dies, it detonates nearby shrapnel and other charged enemies for
      damage. Each charge stack deals additional damage. Charged enemies should
      glow yellow. Show the charge count also on top of the enemy. CHARGE is a
      unique mechanic that will be reused.
  11) [ ] Add HALBERD melee weapon.
  12) [ ] Add LANCE melee weapon.

* POWERUPS
  1) [X] Powerups scale scale with the player's base stats when possible. For
     example, spread/multi should apply a multiplier to the current bullet
     quantity.
  2) [ ] Add SENTRY powerup. This powerup spawns an auto-firing sentry at the
     location of the powerup.

* SKILLS
  1) [X] Remove FAST LEARNER skill.
  2) [X] Remove VAMPIRIC skill.
  3) [ ] Add skill ENGINEER to increase detonator limit.

* VISUALS
  1) [X] Make weapon items distinct from powerups.
  2) [X] Powerups and weapon item drops should have a label underneath them.
  3) [ ] Add cap to explosion radius visual effect.
  4) [X] Show lifebars on large units.

* PERF
  1) [ ] What is the main performance bottleneck?

* DEBUG

* BUGS
  1) [X] Powerups don't seem to affect grenade weapon.
  2) [X] GRENADE weapon type is doing direct damage.

* PRODUCTION
  Platforms: Switch, Steam

* SORT
  Clamp pistol spread arc to 45 degrees.
  Globber spawn. Consumes enemies around itself and adds to its life and size
  Glitter gun. Similar to Scattergun but has special detonation effect.
  Detonator types
  Recoil system.
  Dasher spawn. Moves in quick dashes.
  Spawn type. Resurrects on death.
  Spawn type. Splits on death.
  Phase power up. Walk through enemies without damage.
  Shield is permanent. Goes away after taking hit.
  Flare. Direct damage. 1 round.
  Gravity gun. Pulls units to explosion.
  Debilitating ammo. Crippling powerup.
  Improve shotgun.
