Todo

* HUD
  1) [X] Move weapon and powerup bar to near bottom of screen and make the bars
     and text bigger for readability.

* GAMEPLAY
  1) [ ] Gameplay overhaul. Detonators should now be a finite resource. You
     start with 10 detonations. Detonators spawn randomly around the map at N
     (random) interval. Detonators are a separate pool from powerups and
     weapons, so they're not affected by those particular limits.
  2) [ ] Waves should last longer and each wave should have a theme.

* PLAYER
  1) [X] Level up window is abrupt. Show a level up visual like a golden glow
     around the player then a few seconds later show the screen.

* ENEMY TYPES
  1) [X] Add SPAWNER enemy type. This particular unit is slow and tanky. It
     spawns enemy units around itself until it's destroyed.
  2) [X] Add RUNNER enemy type. This unit is weak but moves more quickly than
     others.
  3) [X] Add ELECTRIC enemy type. This unit spawns an electric field around
     itself every N interval that can damage the player.
  4) [X] Add HIVE enemy type. This units spawns somewhere on the map (not the
     edge. It is larger, immobile, and very tanky. It spawns critter units very
     quickly. Similar to SPAWNER, but more extreme.
  5) [X] Make HIVE unit bigger. It should be differentiated from other large
     enemy units.
  6) [X] HIVE should be much tankier. It's too easy to kill.
  7) [ ] Implement RARE enemy types. Rare units are like normal units but have
     boosted stats. RARE is a modifier applied to an existing unit.
     Differentiate the unit visually. Rare units can also have one or more skills
     (see below).
  8) [ ] Implement enemy skills. Skills are modifiers to stats or abilities. For example:
     - High durability
     - Super high durability
     - Extra speed
     - Smooth (bullets and shrapnel cannot stick to this unit). Can only be
       damaged by detonations.
     - Splits itself in two every N interval (with existing hitpoints).
     - Absorbs bullets and shrapnel around itself every N interval.
     - High regen.
     - Regen field in AoE around itself.
     - Kamikaze. Does extra damage and destroys itself on contact with player.
  9) [ ] FIREWALKER. This enemy unit leaves a trail of damaging fire in its
     wake. It has moderately fast walk speed. Fire trail cannot be damaged. It
     goes away after N seconds.

* WEAPONS
  1) [X] Add currency and weapon system. Enemies give gold on kill. Gold can be
     used to purchase weapons. Weapons can be purchased or switched on the LEVEL
     UP menu.
  2) [X] Add new base weapon types.
  3) [X] Add GRENADE weapon type. It lobs a grenade at the reticle. When it
     lands and explodes, it creates a ring of shrapnel in random directions.
  4) [X] Minigun should fire in a random spray pattern.
  5) [X] Shotgun should have high base projectile velocity.
  6) [ ] Reduce shrapnel count on grenade to 16.

* POWERUPS
  1) [X] Powerups scale scale with the player's base stats when possible. For
     example, spread/multi should apply a multiplier to the current bullet
     quantity.

* SKILLS
  1) [X] Remove FAST LEARNER skill.
  2) [X] Remove VAMPIRIC skill.

* VISUALS
  1) [X] Make weapon items distinct from powerups.
  2) [X] Powerups and weapon item drops should have a label underneath them.

* PERF
  1) [ ] What is the main performance bottleneck?

* DEBUG

* BUGS
  1) [X] Powerups don't seem to affect grenade weapon.
  2) [X] GRENADE weapon type is doing direct damage.

* SORT
  Skill to increase detonator limit. Start with 5.
  Add cap to explosion radius graphic.
  Teleporting enemy type
  Sentry weapon
  Bug weapon. Jumps from enemy to enemy.
  Scattergun. Short range weapon that sprays shrapnel.
  Lobbing animation for grenade
  Switch and Steam port
  Saber, charges enemies
  Halberd
  Lance
  Show life bars on large units
  Globber enemy. Consumes enemies around itself and adds to its life and size
  Glitter gun. Similar to Scattergun but has special detonation effect.
  Detonator types
  Recoil system.
  Dasher enemy. Moves in quick dashes.
  Enemy type. Resurrects on death.
  Enemy type. Splits on death.
  Phase power up. Walk through enemies without damage.
  Shield is permanent. Goes away after taking hit.
  Flare. Direct damage. 1 round.
  Gravity gun. Pulls units to explosion.
  Debilitating ammo. Crippling powerup.
  Improve shotgun.
